version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
    - DATETIME=$(date +"%Y-%m-%d-%H-%M-%S")
  
  pre_build:
    commands:
    - echo "Logging into ECR repository"
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <aws-account-id>.dkr.ecr.<region>.amazonaws.com
  
  build:
    commands:
      - echo Build started on $DATETIME
      - echo Building the Docker image...
      - ls -larth
      - docker build -t serverless-mcp serverless-mcp/server/
      - docker tag serverless-mcp:latest <aws-account-id>.dkr.ecr.<region>..amazonaws.com/<repo-name>:latest

  post_build:
    commands:
      - echo Build completed on $DATETIME
      - echo Pushing the Docker image...
      - docker push <aws-account-id>.dkr.ecr.<region>.amazonaws.com/<repo-name>:latest
      - aws lambda update-function-code --function-name serverless-mcp --image-uri <aws-account-id>.dkr.ecr.<region>.amazonaws.com/<repo-name>:latest




